# Generated by Django 4.2.6 on 2023-10-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('school_name', models.CharField(max_length=200)),
                ('school_address', models.CharField(max_length=200)),
                ('school_zip', models.CharField(max_length=20)),
                ('desription', models.CharField(max_length=400)),
                ('fund_request_amount', models.IntegerField()),
                ('fund_request_months', models.IntegerField()),
                ('fund_approved_amount', models.IntegerField()),
                ('fund_approved_months', models.IntegerField()),
                ('background_cheking', models.BooleanField(default=False)),
                ('background_check_comment', models.CharField(max_length=400)),
                ('application_date', models.DateField()),
                ('application_approval_date', models.DateField()),
                ('isRemoved', models.BooleanField(default=False)),
            ],
        ),
    ]
