# Generated by Django 4.2.6 on 2023-10-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_alter_child_application_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
