# Generated by Django 4.2.6 on 2023-11-01 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_child_photo_child_supporting_document1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='desription',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
