# Generated by Django 4.2.6 on 2023-11-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0009_alter_listofmoralchild_child_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofmoralchild',
            name='parent_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ListofMoralParent',
        ),
    ]
