# Generated by Django 4.2.6 on 2023-11-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0010_alter_listofmoralchild_parent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofmoralchild',
            name='parent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
