# Generated by Django 4.2.6 on 2023-10-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_volunteer_supporting_document1'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='login_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
