# Generated by Django 4.2.6 on 2023-10-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_volunteer_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='application_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='background_check_comment',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='desription',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profession',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
