# Generated by Django 4.2.6 on 2023-11-01 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_alter_volunteer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='supporting_document2',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
