# Generated by Django 4.2.6 on 2023-11-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_parent_login_id_alter_parent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='parent',
            name='supporting_document1',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='parent',
            name='supporting_document2',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='desription',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
