# Generated by Django 4.2.6 on 2023-11-01 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0004_parent_photo_parent_supporting_document1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
