# Generated by Django 4.2.6 on 2023-11-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0006_listofmoralparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofmoralparent',
            name='child_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
